int initializeSingalsHandlers();
int initializeConfig(char *configShareMemoryIdString);
int initializePort(char *portIdString, char *portShareMemoryIdS, char *goodShareMemoryIdS);
int initializePortStruct(char *portIdString, char *portShareMemoryIdS);
int initializeExchangeGoods();
int initializePortGoods(char *goodShareMemoryIdS);
int work();
int waitForStart();
int freePendingMsgs();
int newDay();
int handlePA_ACCEPT(int queueId);
int handlePA_SE_GOOD(int queueId);
int handlePA_RQ_GOOD(int queueId);
int handlePA_EOT();
int generateShareMemory(int sizeOfSegment);
int generateSemaphore(int semKey);
int cleanup();