void initializeSingalsMask();
int initializeSingalsHandlers();
int acknowledgeChildrenStatus(int checkAnalyzerSatus);
int work();
int generateSharedMemory(int sizeOfSegment);
sem_t *generateSemaphore(int semKey);
int generateSubProcesses(int nOfProcess, char *execFilePath, int includeProceduralId, int *arguments, int argSize);
int generateGoods(int firstGenerations);
int cleanup();
void safeExit(int exitNumber);